# Generated by Django 5.0.6 on 2026-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='source',
            field=models.CharField(choices=[('renewal', 'Renewal'), ('calendar', 'Calendar'), ('task', 'Task'), ('leave_request', 'Leave request'), ('ticket', 'Ticket'), ('document', 'Document')], max_length=20),
        ),
    ]
