# Generated by Django 5.0.6 on 2026-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('started', 'Started'), ('waiting_approval', 'Waiting for approval'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
