# Generated by Django 5.0.6 on 2026-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecollateral',
            name='doc_type',
            field=models.CharField(choices=[('experience_letter', 'Experience letter'), ('relieving_letter', 'Relieving letter'), ('salary_certificate', 'Salary certificate')], max_length=30),
        ),
    ]
