# Generated by Django 5.x

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_task_clients(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Client = apps.get_model("sales", "Client")
    by_name = {c.name.lower(): c.id for c in Client.objects.all()}
    for task in Task.objects.filter(client__isnull=True, content_item__isnull=True).exclude(client_name=""):
        cid = by_name.get(task.client_name.strip().lower())
        if cid:
            task.client_id = cid
            task.save(update_fields=["client_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0009_proposal_content_other_service"),
        ("tasks", "0006_task_due_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="sales.client",
            ),
        ),
        migrations.CreateModel(
            name="TaskUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="tasks.task",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(backfill_task_clients, migrations.RunPython.noop),
    ]
