# Generated by Django 5.0.6 on 2026-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
