# Generated by Django 5.0.6 on 2026-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10),
        ),
    ]
